version: '3.8'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cine
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cine
    ports:
      - 4000:3000